#ifndef MARRAZKIAK_H
#define MARRAZKIAK_H

int JOKOA_fondo2();
int JOKOA_fondo1();
int JOKOA_fondo3();
int JOKOA_fondo4();
int JOKOA_fondo4B();
int JOKOA_fondo5();
int JOKOA_fondo6();
int JOKOA_fondo6B();
int JOKOA_fondo7();
int JOKOA_fondo8();
int JOKOA_fondo8B();
int JOKOA_fondo9();
int JOKOA_fondo9B();
int JOKOA_fondo10();
int JOKOA_jokalariaIrudiaSortu();
int JOKOA_npc();
int JOKOA_objetua();
int JOKOA_egurra1();
int JOKOA_egurra2();
int JOKOA_egurra3();
int JOKOA_egurra4();
int JOKOA_egurra5();
int JOKOA_egurra6();
int JOKOA_plastikoa1();
int JOKOA_plastikoa2();
int JOKOA_plastikoa3();
int JOKOA_plastikoa4();
int JOKOA_plastikoa5();
int JOKOA_kablea1();
int JOKOA_kablea2();
int JOKOA_kablea3();
int JOKOA_motxila();
int JOKOA_plaka1();
int JOKOA_plaka2();
int JOKOA_errota1();
int JOKOA_errota2();
int JOKOA_urerrota();

#endif